stages:
  - setup
  - test
  - analysis
  - document
  - deploy

# Set any variables we need
variables:
  MYSQL_DATABASE: $MYSQL_DB
  MYSQL_ROOT_PASSWORD: $MYSQL_PASS
  ELASTIC_URL: $ELASTIC_HOST/phpunit/result
  ELASTIC_HEADER: 'Content-Type: application/json'
  ELASTIC_USER: $ELK_USER
  ELASTIC_PASSWD: $ELK_PASSWD

cache: &global_cache
  paths:
  - vendor/
  - inc/
  key: "$CI_COMMIT_SHORT_SHA"
  policy: pull-push

# Bring in any services we need http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
# See http://docs.gitlab.com/ce/ci/services/README.html for examples.
#  - name: mariadb:10.1
#    alias: database
services:
  - name: mariadb:10.1
    alias: mysql
  - redis:latest

# Each job gets a new fresh service, so we have to initialize each time again
.filldb: &filldb
  before_script:
  - sleep 60
  - echo Did wait for services
  - php -v
  - cat setup/db.sql | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql
  - cat setup/auth.sql | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"
  - cat setup/user.sql | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"
  - php admin/db_prefill.php

websetup:
  stage: setup
  cache:
    <<: *global_cache
    policy: push
  parallel:
    matrix:
      - MYSQLVERSION: mariadb
        PHPVERSION:
          - kai/lggr:7.3
          - kai/lggr:7.4
  image: $CI_REGISTRY/$PHPVERSION
  script:
  - composer --no-interaction --quiet install
  - php -i|grep PDO
  # link our project stuff
  - cd /var/www; mv html html_orig; ln -s /builds/kai/lggr html; ls -l
  - cd /builds/kai/lggr; sed -i "s/localhost/mysql/" inc/Config.php; sed -i "s/localhost/mysql/" inc/AdminConfig.php; sed -i "s/localhost/mysql/" inc/CiConfig.php

unittest:
  stage: test
  <<: *filldb
  allow_failure: true
  cache:
    <<: *global_cache
    paths:
      - logs/junit.xml
      - logs/coverage.xml
  parallel:
    matrix:
      - MYSQLVERSION: mariadb
        PHPVERSION:
          - kai/lggr:7.3
          - kai/lggr:7.4
  image: $CI_REGISTRY/$PHPVERSION
  script:
  - composer test
  after_script:
    - php tests/x2j.php >logs/junit.json
    - curl -X POST -H "${ELASTIC_HEADER}" -u "${ELASTIC_USER}:${ELASTIC_PASSWD}" -d @logs/junit.json "${ELASTIC_URL}" 
  artifacts:
    paths:
      - logs/junit.xml
      - logs/coverage.xml
      - logs/junit.json
    expire_in: 1 month
    reports:
      junit: logs/junit.xml

doctest:
  stage: test
  image: python:3.8-buster
  before_script:
  - pip install -r docs/requirements.txt
  script:
  - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
    - test
  except:
  - master

#webtest:
#  stage: test
#  <<: *filldb
#  allow_failure: true
#  script:
#  - apt-get install -yqq wget
#  - pwd
#  - ls -la
#  - cd /tmp
#  - wget -S -O - http://127.0.0.1/ 

sonarqube:
  stage: analysis
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  cache:
    <<: *global_cache
    paths:
      - .sonar/cache
  before_script:
    - git fetch --unshallow
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - merge_requests
    - develop

makedocs:
  stage: document
  image: python:3.8-buster
  before_script:
  - pip install -r docs/requirements.txt
  - mkdir pub_mkdocs
  script:
  - mkdocs build
  artifacts:
    paths:
    - pub_mkdocs

doxygen:
  stage: document
  image: alpine
  before_script:
  - apk update && apk add doxygen
  - mkdir -p pub_doxygen
  script:
  - doxygen Doxyfile
  artifacts:
    paths:
    - pub_doxygen

pages:
  stage: deploy
  image: alpine
  script:
  - mkdir public
  - cp -a pub_mkdics public/
  - cp -a pub_doxygen public/doxygen/
  artifacts:
    paths:
    - public
