# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: php:7.0-apache

stages:
  - setup
  - test

# Set any variables we need
variables:
  MYSQL_DATABASE: $MYSQL_DB
  MYSQL_ROOT_PASSWORD: $MYSQL_PASS

cache: &global_cache
  paths:
  - vendor/
  - inc/
  key: "$CI_COMMIT_SHORT_SHA"
  policy: pull-push

# Bring in any services we need http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
# See http://docs.gitlab.com/ce/ci/services/README.html for examples.
#  - name: mariadb:10.1
#    alias: database
services:
  - name: mariadb:10.1
    alias: mysql
  - redis:latest

websetup:
  stage: setup
  cache:
    <<: *global_cache
    policy: push
  script:
  - pwd
  - apt-get update -yqq
  - apt-get install -yqq wget git zip
  # Install composer dependencies
  - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
  - php composer.phar --no-interaction --quiet install
  # link our project stuff
  - cd /var/www; mv html html_orig; ln -s /builds/kai/lggr html; ls -l
  - cd /builds/kai/lggr; sed -i "s/localhost/mysql/" inc/Config.php; sed -i "s/localhost/mysql/" inc/AdminConfig.php; sed -i "s/localhost/mysql/" inc/CiConfig.php

unittest:
  stage: test
  before_script:
  - apt-get update -yqq
  - apt-get install -yqq git mysql-client
  - docker-php-ext-install mysqli
  - cat doc/db.sql | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql
  - cat doc/user.sql | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"
  - php admin/db_prefill.php
  script:
  - php composer.phar test

webtest:
  stage: test
  before_script:
  - apt-get update -yqq
  - apt-get install -yqq git mysql-client
  - docker-php-ext-install mysqli
  - cat doc/db.sql | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql
  - cat doc/user.sql | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"
  - php admin/db_prefill.php
  script:
  - pwd
  - ls -la
  - cd /tmp
  - wget -S -O - http://127.0.0.1/

