stages:
  - setup
  - initialize
  - test
  - analysis
  - document
  - deploy

# Set any variables we need
variables:
  LGGR_IMAGE: $CI_REGISTRY/kgroup/lggr:74
  MYSQL_DATABASE: $MYSQL_DB
  MYSQL_ROOT_PASSWORD: $MYSQL_PASS
  DOCKER_AUTH_CONFIG: '{ "auths": { "https://index.docker.io/v1/": { "auth": "$DOCKER_AUTH" } }}'
  SELENIUM_URL: $SELENIUM_URL

websetup:
  stage: setup
  tags:
    - docker
  image: $LGGR_IMAGE
  rules:
    - if: '$DODOCKER != "yes"'
  script:
  - composer --no-interaction --quiet install
  - composer npm-install
  - php -i|grep PDO
  # link our project stuff
  - rm .htaccess
  - cd /var/www; mv html html_orig; ln -s /builds/kgroup/lggr html; ls -l
  artifacts:
    name: "web"
    paths:
      - vendor/
      - node_modules/
      - inc/
      - composer.lock

dbsetup:
  stage: initialize
  tags:
    - docker
  image: $LGGR_IMAGE
  rules:
    - if: '$DODOCKER != "yes"'
  services:
  - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/mariadb:10.1
    alias: mysql
  - ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/redis:latest
  script:
  - sleep 60
  - echo Did wait for services
  - cat setup/1_db.sql | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql
  - cat setup/2_auth.sql | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"
  - cat setup/3_user.sql | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql
  - php admin/db_prefill.php
  - mysqldump --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql --opt "$MYSQL_DATABASE" >dump.sql
  dependencies:
    - websetup
  artifacts:
    name: "database"
    paths:
      - dump.sql

dodocker:
  stage: initialize
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:20.10.17
  rules:
    - if: '$DODOCKER == "yes"'
  parallel:
    matrix:
      - D: ['74', '81', 'mkdocs', 'doxygen']
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:20-dind
      alias: docker
  tags:
    - docker
  before_script:
    - mkdir -p $HOME/.docker
    - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  script:
    - docker build -t registry.kretschmann.software/kgroup/lggr:$D . -f Dockerfile_$D
    - docker push registry.kretschmann.software/kgroup/lggr:$D

unittest:
  stage: test
  tags:
    - docker
  image: $LGGR_IMAGE
  rules:
    - if: '$DODOCKER != "yes"'
  services:
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/mariadb:10.1
      alias: mysql
    - ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/redis:latest
  before_script:
    - ls -l dump.sql composer.lock
    - mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE" <dump.sql
    - cat setup/3_user.sql | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql
  script:
    - composer test
  after_script:
    - php tests/x2j.php >logs/junit.json
  dependencies:
    - websetup
    - dbsetup
  artifacts:
    name: "test"
    paths:
      - logs/junit.xml
      - logs/coverage.xml
      - logs/junit.json
      - pub_phpunit
    expire_in: 1 month
    reports:
      junit: logs/junit.xml
#      cobertura: logs/coverage.xml

webtest:
  stage: test
  tags:
    - docker
  image: $LGGR_IMAGE
  rules:
    - if: '$DODOCKER != "yes"'
  services:
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/mariadb:10.1
      alias: mysql
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/selenium/standalone-chrome
      alias: selenium
    - ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/redis:latest
  before_script:
    - ls -l dump.sql composer.lock
    - mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE" <dump.sql
    - cat setup/3_user.sql | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql
    - rm .htaccess
    - cd /var/www; mv html html_orig; ln -s /builds/kgroup/lggr html; ls -l
    - /etc/init.d/apache2 start
  script:
    - cd /builds/kgroup/lggr
    - WEBIP=`hostname -i` composer webtest
  allow_failure: true
  dependencies:
    - websetup
    - dbsetup
  artifacts:
    paths:
      - logs/webtest_junit.xml
    reports:
      junit: logs/webtest_junit.xml

doctest:
  stage: test
  tags:
    - docker
  image: $CI_REGISTRY/kgroup/lggr:mkdocs
  rules:
    - if: '$DODOCKER != "yes" && $CI_COMMIT_BRANCH == "master"'
  before_script:
    - mkdir test
  script:
    - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
    - test

bom:
  stage: analysis
  tags:
    - docker
  variables:
    DTRACK_URL: ${DTRACK_URL}
    DTRACK_API: ${DTRACK_API}
    DTRACK_NAME: "lggr"
  image: $LGGR_IMAGE
  rules:
    - if: '$DODOCKER != "yes"'
  script:
    - composer CycloneDX:make-sbom
  after_script:
    - 'export DTRACK_VERSION=$(cut -d ":" -f 6 <VERSION.cpe)'
    - echo "projectName=${DTRACK_NAME}"
    - echo "projectVersion=${DTRACK_VERSION}"
    - 'curl -X POST ${DTRACK_URL}api/v1/bom -H "Content-Type: multipart/form-data" -H "X-API-Key: ${DTRACK_API}" -F "autoCreate=true" -F "projectName=${DTRACK_NAME}" -F "projectVersion=${DTRACK_VERSION}" -F bom=@bom.xml'
  allow_failure: false
  artifacts:
    paths:
      - bom.xml

sonarqube:
  stage: analysis
  tags:
    - docker
  image:
    name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  rules:
    - if: '$DODOCKER != "yes"'
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  before_script:
    - git fetch --unshallow
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.branch.name=${CI_COMMIT_REF_SLUG}
  allow_failure: true

makedocs:
  stage: document
  tags:
    - docker
  image: $CI_REGISTRY/kgroup/lggr:mkdocs
  rules:
    - if: '$DODOCKER != "yes"'
  before_script:
    - mkdir pub_mkdocs
  script:
    - mkdocs build
  artifacts:
    paths:
    - pub_mkdocs

doxygen:
  stage: document
  tags:
    - docker
  image: $CI_REGISTRY/kgroup/lggr:doxygen
  rules:
    - if: '$DODOCKER != "yes"'
  before_script:
    - mkdir -p pub_doxygen
  script:
    - doxygen Doxyfile
  artifacts:
    paths:
    - pub_doxygen

pages:
  stage: deploy
  tags:
    - docker
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/alpine:latest
  rules:
    - if: '$DODOCKER != "yes"'
  before_script:
    - mkdir public
  script:
    - cp -a pub_mkdocs/* public/
    - cp -a pub_doxygen/html/* public/doxygen/
    - cp -a pub_phpunit/* public/phpunit/
  artifacts:
    paths:
    - public

deploy:
  stage: deploy
  tags:
    - docker
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/curlimages/curl:latest
  rules:
    - if: '$DODOCKER != "yes"'
  variables:
    URL: "$CI_SERVER_PROTOCOL://$CI_SERVER_HOST:$CI_SERVER_PORT/api/v4/projects/$CI_PROJECT_ID/packages/composer?job_token=$CI_JOB_TOKEN"
  script:
    - version=$([[ -z "$CI_COMMIT_TAG" ]] && echo "branch=$CI_COMMIT_REF_NAME" || echo "tag=$CI_COMMIT_TAG")
    - insecure=$([ "$CI_SERVER_PROTOCOL" = "http" ] && echo "--insecure" || echo "")
    - response=$(curl -s -w "\n%{http_code}" $insecure --data $version $URL)
    - code=$(echo "$response" | tail -n 1)
    - body=$(echo "$response" | head -n 1)
    # Output state information
    - if [ $code -eq 201 ]; then
        echo "Package created - Code $code - $body";
      else
        echo "Could not create package - Code $code - $body";
        exit 1;
      fi
