FROM php:7.4-apache
MAINTAINER Kai Kretschmann

RUN apt-get update && apt-get install -y \
	mariadb-client curl wget git zip npm
RUN pecl install xdebug-3.1.5 && docker-php-ext-enable xdebug
RUN pecl install -D 'enable-redis-igbinary="no" enable-redis-lzf="no" enable-redis-zstd="no"' redis
RUN docker-php-ext-enable redis
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install mysqli

RUN wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig \
&& php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
&& php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
&& php composer-setup.php && mv composer.phar /usr/bin/composer \
&& php -r "unlink('composer-setup.php'); unlink('installer.sig');"
